
    - name: Install aptitude
      apt: pkg=aptitude
      become: yes

    - name: Apt update/upgrade
      apt: upgrade=yes update_cache=yes
      become: yes

    - name: Install tmux terminal multiplexer
      apt: pkg=tmux
      become: yes

    - name: Install required packages
      apt: pkg={{ item }}
      become: yes
      with_items:
      - git
      - cmake
      - libleveldb-dev
      - libjsoncpp-dev
      - libjsonrpccpp-dev
      - libboost-all-dev
      - libgmp-dev
      - libreadline-dev
      - libcurl4-gnutls-dev
      - ocl-icd-libopencl1
      - opencl-headers
      - mesa-common-dev
      - libmicrohttpd-dev
      - build-essential

    - name: Download CUDA repository .deb
      get_url: url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb dest=/tmp/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      register: get_deb_result
      until: get_deb_result | succeeded
      retries: 3
      delay: 1

    - name: Install CUDA repository
      apt: deb=/tmp/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      become: yes

    - name: Add ethereum repositories
      apt_repository: repo={{ item }} update_cache=yes
      become: yes
      with_items:
      - ppa:ethereum/ethereum

    - name: Install CUDA
      apt: pkg=cuda
      become: yes

    - name: Install CryptoPP
      apt: pkg={{ item }}
      become: yes
      with_items:
      - libcryptopp-utils
      - libcryptopp-dev

    - name: Install ethereum CLI tools
      apt: pkg={{ item }}
      become: yes
      with_items:
      - ethereum

    - name: Get cpp-ethereum
      git: repo=https://github.com/Genoil/cpp-ethereum/ dest=~/cpp-ethereum

    - name: Setup build directory
      file: path=~/cpp-ethereum/build state=directory

    - name: cmake cpp-ethereum
      command: cmake -DBUNDLE=cudaminer .. chdir=~/cpp-ethereum/build

    - name: make cpp-ethereum
      command: make -j8 chdir=~/cpp-ethereum/build
